# Generated by Django 6.1.1 on 2026-09-25 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('price_mismatch', 'Landlord did not follow declared price of unit'), ('offensive_statements', 'Listing included offensive statements'), ('misleading_info', 'Misleading photos or information'), ('unresponsive', 'Landlord was unresponsive or unprofessional'), ('safety_concerns', 'Safety concerns / suspicious activity'), ('policy_violation', 'Violation of platform rules or policies'), ('fraudulent_listing', 'Fraudulent listing (fake or duplicate)'), ('others', 'Others (please specify)'), ('no_show', 'Renter did not show up to a scheduled visit'), ('harassment', 'Renter was abusive or harassing'), ('fake_inquiry', 'Fake or spam inquiry')], max_length=50)),
                ('other_category_text', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Review'), ('reviewing', 'Undergoing Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='report_evidence/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core_reports.report')),
            ],
        ),
    ]
