from datetime import datetime


class Users:

    def __init__(self, first_name, last_name, sex, password, phone_number, role, user_id=None, is_verified=False):
        self.user_id = user_id
        self.first_name = first_name.title()
        self.last_name = last_name.title()
        self.sex = sex
        self.username = self._generate_username(first_name, last_name)
        self.password = password
        self.phone_number = phone_number
        self.role = role
        self.created_at = datetime.now()
        self.is_verified = is_verified

        # password_hash changed to password for the meantime
        # removed username and created_at in the parameters; values are generated by default

    def _generate_username(self, first_name, last_name):
        generatedUsername = f"{first_name.title()} {last_name.title()}"
        return generatedUsername
        # generates user name by capitalizing the first letter then lowering the rest using .title()

    def display_user_info(self):
        print(f"User ID: {self.user_id}")
        print(f"Username: {self.username}")
        print(f"First Name: {self.first_name}")
        print(f"Last Name: {self.last_name}")
        print(f"Sex: {self.sex}")
        print(f"Phone Number: {self.phone_number}")
        print(f"Role: {self.role}")

    def logIn(self, username, password):
        if self.username == username and self.password == password:
            print ("Logged in Successfully!")
            return True
        else:
            print ("Wrong username or password")
            return False

    def logOut(self):
        print(f"{self.username} has logged out.")
        return True

# format: from filename import class_name