# Generated by Django 6.1.1 on 2026-10-02 04:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_user_table_landlord_renter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_name', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('landmark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.CharField(choices=[('school', 'School'), ('healthcenter', 'Hospital / Clinic'), ('market', 'Market'), ('pharmacy', 'Pharmacy / Drugstore'), ('bank', 'Bank'), ('restaurant', 'Restaurant / Eatery'), ('terminal', 'Transport Terminal'), ('airport', 'Airport'), ('church', 'Church'), ('government', 'Government Office'), ('mall', 'Mall'), ('park', 'Park'), ('gym', 'Gym'), ('other', 'Other')], max_length=25)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('complex_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complex_name', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('complex_description', models.TextField()),
                ('pet_friendly', models.BooleanField(default=False)),
                ('sex_restriction', models.CharField(choices=[('male_only', 'Male only'), ('female_only', 'Female only'), ('any', 'Any')], default='any', max_length=12)),
                ('has_parking_space', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unpublished', 'Unpublished')], default='unpublished', max_length=12)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complexes', to='core_listings.area')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='core.landlord')),
            ],
            options={
                'verbose_name_plural': 'complexes',
            },
        ),
        migrations.CreateModel(
            name='ComplexPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='complex_pictures/')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core_listings.complex')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.PositiveIntegerField()),
                ('travel_minutes', models.PositiveSmallIntegerField()),
                ('travel_mode', models.CharField(default='driving', max_length=10)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='core_listings.complex')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_listings.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.PositiveSmallIntegerField()),
                ('bedroom_type', models.CharField(choices=[('studio', 'Studio'), ('one_bedroom', 'Single bedroom'), ('two_bedroom', '2 bedrooms'), ('three_plus', '3 or more')], max_length=12)),
                ('length_dimension', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('width_dimension', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('air_conditioned', models.BooleanField(default=False)),
                ('furnish_level', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-furnished'), ('fully_furnished', 'Fully furnished')], max_length=15)),
                ('max_occupant', models.PositiveSmallIntegerField()),
                ('unit_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('lease_term', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('biannual', 'Biannual (6 months)'), ('annual', 'Annual (12 months)')], default='monthly', max_length=10)),
                ('deposit_months', models.PositiveSmallIntegerField(default=0)),
                ('advance_months', models.PositiveSmallIntegerField(default=0)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('unpublished', 'Unpublished')], default='available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core_listings.complex')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='unit_pictures/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core_listings.unit')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='complex',
            constraint=models.UniqueConstraint(fields=('landlord', 'complex_name'), name='unique_complex_name_per_landlord'),
        ),
        migrations.AddConstraint(
            model_name='complexpicture',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('complex',), name='one_cover_per_complex'),
        ),
        migrations.AlterUniqueTogether(
            name='complexlandmark',
            unique_together={('complex', 'landmark', 'travel_mode')},
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('complex', 'identifier'), name='unique_unit_identifier_per_complex'),
        ),
        migrations.AddConstraint(
            model_name='unitpicture',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('unit',), name='one_cover_per_unit'),
        ),
    ]
