# Generated by Django 6.1.1 on 2026-10-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='lease_term',
        ),
        migrations.AddField(
            model_name='complex',
            name='lease_term',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('biannual', 'Biannual (6 months)'), ('annual', 'Annual (12 months)')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='complex',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
